### ISSUE TITLE
Out of bound read in stp_print()

### ISSUE THREAD

**Issue by fumfel** [the-tcpdump-group/tcpdump#550]
**Out of bound read in stp_print()** 

Tested on Git HEAD:  e2adb166ecaf59555e18787e86ac8c828efa0acc

To reproduce: `tcpdump -r heap_bufover_4.pcap`

![Crashing test case - please change extension to '.pcap'](https://cloud.githubusercontent.com/assets/5985287/19833342/90300f02-9e3e-11e6-8593-e43f51bae0da.png)

ASAN output:

```
=================================================================
==21310==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000ef34 at pc 0x000000680fae bp 0x7ffe46a07e70 sp 0x7ffe46a07e68
READ of size 1 at 0x60300000ef34 thread T0
    #0 0x680fad in stp_print XYZ/tcpdump/./print-stp.c:396:5
    #1 0x5cd44d in llc_print XYZ/tcpdump/./print-llc.c:278:3
    #2 0x565d27 in ether_print XYZ/tcpdump/./print-ether.c:171:16
    #3 0x501b12 in pretty_print_packet XYZ/tcpdump/./print.c:339:18
    #4 0x4eebeb in print_packet XYZ/tcpdump/./tcpdump.c:2492:2
    #5 0x7adaf7 in pcap_offline_read XYZ/libpcap/./savefile.c:527:4
    #6 0x6b6f4c in pcap_loop XYZ/libpcap/./pcap.c:890:8
    #7 0x4ea1db in main XYZ/tcpdump/./tcpdump.c:1996:12
    #8 0x7f660ee1682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x419ff8 in _start (/usr/local/sbin/tcpdump+0x419ff8)

0x60300000ef34 is located 0 bytes to the right of 20-byte region [0x60300000ef20,0x60300000ef34)
allocated by thread T0 here:
    #0 0x4b880c in malloc /home/development/llvm/3.9.0/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x7af103 in pcap_check_header XYZ/libpcap/./sf-pcap.c:401:14
    #2 0x7acf22 in pcap_fopen_offline_with_tstamp_precision XYZ/libpcap/./savefile.c:400:7
    #3 0x7accaf in pcap_open_offline_with_tstamp_precision XYZ/libpcap/./savefile.c:307:6
    #4 0x7f660ee1682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow XYZ/tcpdump/./print-stp.c:396:5 in stp_print
Shadow bytes around the buggy address:
  0x0c067fff9d90: 00 00 00 00 fa fa 00 00 00 01 fa fa 00 00 04 fa
  0x0c067fff9da0: fa fa 00 00 07 fa fa fa 00 00 00 01 fa fa 00 00
  0x0c067fff9db0: 00 02 fa fa 00 00 00 01 fa fa 00 00 06 fa fa fa
  0x0c067fff9dc0: 00 00 00 fa fa fa 00 00 07 fa fa fa 00 00 06 fa
  0x0c067fff9dd0: fa fa 00 00 07 fa fa fa 00 00 00 00 fa fa fd fd
=>0x0c067fff9de0: fd fa fa fa 00 00[04]fa fa fa 00 00 04 fa fa fa
  0x0c067fff9df0: 00 00 05 fa fa fa 00 00 04 fa fa fa 00 00 04 fa
  0x0c067fff9e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9e10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9e20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9e30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21310==ABORTING
```

**Comment by fxlb** [comment]
Fixed with commit 286042515f93fe1a615fd1364967683370443d0e.

**Comment by infrastation** [comment]
This is a duplicate of #547. Please send any future security reports to security@tcpdump.org.

**Comment by guyharris** [comment]
Duplicate of #547
