### ISSUE TITLE
Heap out of bounds read in stp_print() 1

### ISSUE THREAD

**Issue by fumfel** [the-tcpdump-group/tcpdump#555]
**Heap out of bounds read in stp_print() 1**

Tested on Git HEAD:  e2adb166ecaf59555e18787e86ac8c828efa0acc

To reproduce: `tcpdump -r oobr_stp_print.pcap`

![Crashing test case - please change extension to '.pcap'](https://cloud.githubusercontent.com/assets/5985287/20091058/ee96c17c-a590-11e6-99fb-913f88fa92b4.png)

ASAN output:

```
==10022==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60600000eff4 at pc 0x000000681b47 bp 0x7ffdf80b7e90 sp 0x7ffdf80b7e88
READ of size 1 at 0x60600000eff4 thread T0
    #0 0x681b46 in stp_print XYZ/tcpdump/./print-stp.c:419:27
    #1 0x5cdf8d in llc_print XYZ/tcpdump/./print-llc.c:278:3
    #2 0x565d07 in ether_print XYZ/tcpdump/./print-ether.c:171:16
    #3 0x501b12 in pretty_print_packet XYZ/tcpdump/./print.c:339:18
    #4 0x4eebeb in print_packet XYZ/tcpdump/./tcpdump.c:2492:2
    #5 0x7ae607 in pcap_offline_read XYZ/libpcap/./savefile.c:527:4
    #6 0x6b7a7c in pcap_loop XYZ/libpcap/./pcap.c:890:8
    #7 0x4ea1db in main XYZ/tcpdump/./tcpdump.c:1996:12
    #8 0x7f1cc65d282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x419ff8 in _start (/usr/local/sbin/tcpdump+0x419ff8)

0x60600000eff4 is located 2 bytes to the right of 50-byte region [0x60600000efc0,0x60600000eff2)
allocated by thread T0 here:
    #0 0x4b880c in malloc /home/development/llvm/3.9.0/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x7afc13 in pcap_check_header XYZ/libpcap/./sf-pcap.c:401:14
    #2 0x7ada32 in pcap_fopen_offline_with_tstamp_precision XYZ/libpcap/./savefile.c:400:7
    #3 0x7ad7bf in pcap_open_offline_with_tstamp_precision XYZ/libpcap/./savefile.c:307:6
    #4 0x7f1cc65d282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow XYZ/tcpdump/./print-stp.c:419:27 in stp_print
Shadow bytes around the buggy address:
  0x0c0c7fff9da0: fa fa fa fa 00 00 00 00 00 00 04 fa fa fa fa fa
  0x0c0c7fff9db0: 00 00 00 00 00 00 06 fa fa fa fa fa 00 00 00 00
  0x0c0c7fff9dc0: 00 00 06 fa fa fa fa fa 00 00 00 00 00 00 07 fa
  0x0c0c7fff9dd0: fa fa fa fa 00 00 00 00 00 00 07 fa fa fa fa fa
  0x0c0c7fff9de0: 00 00 00 00 00 00 07 fa fa fa fa fa fd fd fd fd
=>0x0c0c7fff9df0: fd fd fd fd fa fa fa fa 00 00 00 00 00 00[02]fa
  0x0c0c7fff9e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9e10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9e20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9e30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9e40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10022==ABORTING
```

**Comment by fxlb** [comment]
Fixed with commit 286042515f93fe1a615fd1364967683370443d0e.

**Comment by infrastation** [comment]
This is a duplicate of #547. Please send any future security reports to security@tcpdump.org.

**Comment by guyharris** [comment]
Duplicate of #547
