### ISSUE TITLE
Heap out of bounds read in lookup_nsap()

### ISSUE THREAD

**Issue by fumfel** [the-tcpdump-group/tcpdump#563]
**Heap out of bounds read in lookup_nsap()**

Tested on Git HEAD:  e2adb166ecaf59555e18787e86ac8c828efa0acc

To reproduce: `tcpdump -r oobr_lookup_nsap.pcap`

![Crashing test case - please change extension to '.pcap'](https://cloud.githubusercontent.com/assets/5985287/20091727/973bc3ec-a594-11e6-9a53-a46ce7e08b03.png)

ASAN output:

```
==6967==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60400000e08b at pc 0x0000004f575d bp 0x7fff98fbf6c0 sp 0x7fff98fbf6b8
READ of size 1 at 0x60400000e08b thread T0
    #0 0x4f575c in lookup_nsap XYZ/tcpdump/./addrtoname.c:417:8
    #1 0x4f575c in isonsap_string XYZ/tcpdump/./addrtoname.c:657
    #2 0x5b69be in clnp_print XYZ/tcpdump/./print-isoclns.c:813:13
    #3 0x5a917a in isoclns_print XYZ/tcpdump/./print-isoclns.c:687:8
    #4 0x566ecc in ethertype_print XYZ/tcpdump/./print-ether.c:357:3
    #5 0x5663f8 in ether_print XYZ/tcpdump/./print-ether.c:229:7
    #6 0x501b12 in pretty_print_packet XYZ/tcpdump/./print.c:339:18
    #7 0x4eebeb in print_packet XYZ/tcpdump/./tcpdump.c:2492:2
    #8 0x7ae607 in pcap_offline_read XYZ/libpcap/./savefile.c:527:4
    #9 0x6b7a7c in pcap_loop XYZ/libpcap/./pcap.c:890:8
    #10 0x4ea1db in main XYZ/tcpdump/./tcpdump.c:1996:12
    #11 0x7fbb5455782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #12 0x419ff8 in _start (/usr/local/sbin/tcpdump+0x419ff8)

AddressSanitizer can not describe address in more detail (wild memory access suspected).
SUMMARY: AddressSanitizer: heap-buffer-overflow XYZ/tcpdump/./addrtoname.c:417:8 in lookup_nsap
Shadow bytes around the buggy address:
  0x0c087fff9bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9bd0: fa fa 00 00 00 00 00 fa fa fa 00 00 00 00 00 fa
  0x0c087fff9be0: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x0c087fff9bf0: fa fa 00 00 00 00 00 02 fa fa 00 00 00 00 00 01
  0x0c087fff9c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c087fff9c10: fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c087fff9c60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==6967==ABORTING
```

**Comment by infrastation** [comment]
Commit 2817174 fixes this and the fix is available in the release 4.9.0. Thank you very much for the report, please send any future security reports to security@tcpdump.org.
