### ISSUE TITLE
Out of bounds read when parsing a MEDSA packet capture

### ISSUE THREAD

**Issue by mgv** [the-tcpdump-group/tcpdump#580]
Hi there!

This bug was found with AFL and tested against https://github.com/the-tcpdump-group/tcpdump/tree/17a3c288589e18b9f1299fdf350852c768e2e887

Base64 encoded pcap file:
```
1MOyoTAwMDAwMDAwMDAwMDAwMABrAAAwMDAwMDAwMDBnAAAAAAAAMDAw69raMDAwMDA6AAAAMDAw
69raMDAwMDAwCABFMAA7MDBAADARMDB/AP8wAQAAAzAwAKEwMDAwMBwCADCWMDAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMDAwMDAwMDAwMEoAAAD0MDAwMDAwMDAwMDAwMDAwCABFMAA7MDBAADARMDB/
AP8wAQAAAzAwAKEwMDAwMBwCADCWMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
```
Run `tcpdump -r file.pcap` to reproduce the issue.

```
(gdb) run -r /home/vagrant/crash_fr 
Starting program: /home/vagrant/tcpdump_git/tcpdump/tcpdump -r /home/vagrant/crash_fr
reading from file /home/vagrant/crash_fr, link-type FRELAY (Frame Relay)

Program received signal SIGSEGV, Segmentation fault.
etheraddr_string (ndo=ndo@entry=0xbfffe448, ep=ep@entry=0xb792efff <error: Cannot access memory at address 0xb792efff>) at ./addrtoname.c:486
486             tp = lookup_emem(ndo, ep);

(gdb) bt
#0  etheraddr_string (ndo=ndo@entry=0xbfffe448, ep=ep@entry=0xb792efff <error: Cannot access memory at address 0xb792efff>) at ./addrtoname.c:486
#1  0x08088f3d in llc_print (ndo=ndo@entry=0xbfffe448, p=0xb792f019 "\353\332\332\060\060\060\060\060\060\b", p@entry=0xb792f015 "", length=805306351, length@entry=805306355, caplen=805306351, caplen@entry=805306355, esrc=esrc@entry=0xb792f005 "@0", 
    edst=edst@entry=0xb792efff <error: Cannot access memory at address 0xb792efff>) at ./print-llc.c:346
#2  0x0808e4b2 in medsa_print (ndo=ndo@entry=0xbfffe448, bp=0xb792f015 "", bp@entry=0xb792f00d "00000:", length=805306355, length@entry=805306363, caplen=805306355, caplen@entry=805306363) at ./print-medsa.c:163
#3  0x0806cec5 in ethertype_print (ndo=ndo@entry=0xbfffe448, ether_type=ether_type@entry=56026, p=0xb792f00d "00000:", length=805306363, caplen=805306363) at ./print-ether.c:430
#4  0x0807105d in fr_print (ndo=0xbfffe448, p=0xb792f008 "00\353\332\332\060\060\060\060\060:", length=805306368) at ./print-fr.c:276
#5  0x080511c3 in pretty_print_packet (ndo=ndo@entry=0xbfffe448, h=h@entry=0xbfffe320, sp=sp@entry=0xb792f008 "00\353\332\332\060\060\060\060\060:", packets_captured=1) at ./print.c:339
#6  0x0804d907 in print_packet (user=0xbfffe448 "", h=0xbfffe320, sp=0xb792f008 "00\353\332\332\060\060\060\060\060:") at ./tcpdump.c:2492
#7  0xb7e05b26 in ?? () from /usr/lib/i386-linux-gnu/libpcap.so.0.8
#8  0xb7df5e1f in pcap_loop () from /usr/lib/i386-linux-gnu/libpcap.so.0.8
#9  0x0804c4b8 in main (argc=3, argv=0xbffff684) at ./tcpdump.c:1996
```

The faulty assignment seems to take place on line 147 of the `print_medsa.c` file.

```
138: void
139: medsa_print(netdissect_options *ndo,
140:	    const u_char *bp, u_int length, u_int caplen)
141: {
142:	register const struct ether_header *ep;
143:	const struct medsa_pkthdr *medsa;
144:	u_short ether_type;
145:
146:	medsa = (const struct medsa_pkthdr *)bp;
147:	ep = (const struct ether_header *)(bp - sizeof(*ep));
        [...]
```
The variable `ep` is set to `bp - 0xe` and is left pointing before the beginning of the mapped area, causing a SIGSEGV on the next read.

**Comment by infrastation** [comment]
Don't worry, there **is** a problem in that code, it was reported before and is already being looked into. Thank you for the report anyway. Just leave it with us and it will be sorted. Same stands for issue #581.

**Comment by guyharris** [comment]
Yes, see #581 for 1) the reason why you need to take some checks out of current libpcap to try to reproduce it and 2) the story of the fix.

**Comment by guyharris** [comment]
Denis's fix is in the security branch (Will be merged in a few weeks).

**Comment by infrastation** [comment]
The fix to RRCP and MEDSA wasn't mine, perhaps it will make sense to double-check everything later.

**Comment by infrastation** [comment]
The original reporter for this vulnerability is Hanno Böck. It took a long time to publish the fix so the same issue was later independently discovered by other researchers.

Commits 6bc4429 and cae54f4 fix this and the fix is available in the release 4.9.0. Thanks to everybody for their reports, please send any future security reports to security@tcpdump.org.
